### ISSUE TITLE
Кнопка "Крестик" после создания диспута не ведет на главную страницу

### ISSUE THREAD

**Issue by alexhitory** [management-of-dispute-resolution/dispute_resolution_frontend#100]
Предусловие:
1.Открыть браузер
2.Перейти по ссылке [https://ccdia.acceleratorpracticum.ru](https://ccdia.acceleratorpracticum.ru/)
3.Авторизоваться как пользователь
email: alexey@example.com
пароль: Multipass123
Шаги:
1. Нажать на кнопку "Создать обращение"
2. Заполнить поля валидными значениями
3. Нажать на кнопку "Продолжить"
4. В окне открывшегося обращения нажать на "Крестик"
ОР: Осуществится переход на главную страницу
ФР: Переходит на форму "Создать обращение"
Окружение: 
FireFox 119.0.1, 2560х1440 ;
Chrome 119.0.6045.123, 1920х1080;
Safari 17.1, 1280х1024

**Comment by CadSergRF** [comment]
Необходимо исправить navigate в компоненте по роуту /:{id}

**Comment by BarahBabah** [comment]
> Необходимо исправить navigate в компоненте по роуту /:{id}

скорее на /disputes
